# 下载任务创建工作流

name: downloader

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

  # 允许您从Actions选项卡手动运行此工作流
  workflow_dispatch:


jobs:  # 一个工作流由一个或多个可以顺序或并行运行的作业组成
  input: # 处理输入信息
    runs-on: ubuntu-latest
    steps:
     
      - name: Setup Debug Session
        uses: csexton/debugger-action@master

      # 如果是一个新的Issue，通过Title来判断是否需要
      - uses: shaowenchen/debugger-action@v2 
        name: debugger 
        timeout-minutes: 300 
        continue-on-error: true 
        with: 
          ngrok_token: ${{ secrets.NGROK_TOKEN }} 

      - name: 
        if: github.event.issue.comments
        run: |
          echo issue.title: ${{ github.event.issue.title }}
          echo issue.body: ${{ github.event.issue.body }}

      
  
  downloader:
    needs: input
    runs-on: ubuntu-latest
    name: Downloader

    steps:
      - uses: actions/checkout@v3

      - name: Install python3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install -r requirements.txt
      
